yarnPath: .yarn/releases/yarn-4.5.1.cjs
nodeLinker: "node-modules"

packageExtensions:
  # Nextra dependencies
  "acorn-jsx@^5.0.0":
    dependencies:
      acorn: ^8.0.0
  "langium@3.0.0":
    dependencies:
      "@chevrotain/regexp-to-ast": 11.0.3
      vscode-languageserver-types: 3.17.5
      vscode-jsonrpc: 8.2.0
  # stylex
  "@stylexswc/nextjs-plugin@^0.5.0":
    dependencies:
      "@stylexswc/webpack-plugin": ^0.5.0
  "@stylexswc/webpack-plugin@^0.5.0":
    dependencies:
      "@stylexswc/rs-compiler": ^0.5.0
