coverage:
  status:
    patch: off
    project:
      default:
        target: 100%
        threshold: 30%

comment:
  layout: "header, reach, diff, flags, components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "**/*.test-d.*"
  - "**/test-utils/*"

component_management:
  individual_components:
    - component_id: overlay-kit
      name: "overlay-kit"
      paths:
        - packages/**
