name: CI

on:
  push:
    branches: [main, beta]
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          [
            'pnpm --filter @banksalad/overlay-kit run test',
            'pnpm --filter @banksalad/overlay-kit run test:attw',
            'pnpm --filter @banksalad/overlay-kit run test:publint',
            'pnpm lint',
            'pnpm --filter @overlay-kit/framer-motion-react-18 run build',
            'pnpm --filter @overlay-kit/framer-motion-react-19 run build',
          ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm --filter @banksalad/overlay-kit run build

      - name: Run command
        run: ${{ matrix.command }}
      - if: matrix.command == 'pnpm --filter @banksalad/overlay-kit run test'
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
